apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: moodle-pdb
  namespace: moodle
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: moodle
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: moodle
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: postgres
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pgbouncer-pdb
  namespace: moodle
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: pgbouncer
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-pdb
  namespace: moodle
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: redis
