apiVersion: v1
kind: ServiceAccount
metadata:
  name: moodle
  namespace: moodle
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: moodle
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgbouncer
  namespace: moodle
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: moodle
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: moodle-role
  namespace: moodle
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: moodle-rolebinding
  namespace: moodle
subjects:
- kind: ServiceAccount
  name: moodle
  namespace: moodle
roleRef:
  kind: Role
  name: moodle-role
  apiGroup: rbac.authorization.k8s.io
