apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
  namespace: moodle
spec:
  replicas: 1   # can scale horizontally only if moodledata is shared on RWX storage
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 33
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: moodle
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: postgres
              topologyKey: kubernetes.io/hostname
      containers:
      - name: moodle
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        image: moodlehq/moodle-php-apache:8.3
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: moodle-config
        env:
        - name: MOODLE_DOCKER_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moodle-secrets
              key: db-password
        - name: MOODLE_DOCKER_ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: moodle-secrets
              key: admin-password
        - name: MOODLE_DOCKER_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: moodle-secrets
              key: moodle-secret-key
        - name: MOODLE_DOCKER_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moodle-secrets
              key: redis-password
        ports:
        - containerPort: 80
        volumeMounts:
        - name: moodledata
          mountPath: /var/www/moodledata
        - name: tmp
          mountPath: /tmp
        - name: php-conf
          mountPath: /usr/local/etc/php/conf.d
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
      volumes:
      - name: moodledata
        persistentVolumeClaim:
          claimName: moodledata-pvc
      - name: tmp
        emptyDir: {}
      - name: php-conf
        emptyDir: {}
