apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-pvc
  namespace: moodle
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard   # override via Kustomize to match your cluster
  resources:
    requests:
      storage: 10Gi
